name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    name: Build and Publish Docker Image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      actions: read
      id-token: write

    steps:
      # Étape 1: Checkout du dépôt
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2: Connexion au registre GitHub Packages
      - name: Log in to GitHub Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Étape 3: Build de l'image Docker
      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/samada25/${{ github.event.repository.name }}:latest .


      # Étape 7: Pousser l'image Docker dans le registre GitHub Packages
      - name: Push Docker Image to GitHub Packages
        run: |
          docker push ghcr.io/samada25/${{ github.event.repository.name }}:latest
