name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    name: Build and Publish Docker Image
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to the GitHub Container Registry
      - name: Log in to GitHub Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build the Docker image
      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/samada58/${{ github.event.repository.name }}:latest .

      # Scan Docker Image with Trivy (with cache and retry logic)
      - name: Scan Docker Image for vulnerabilities
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: ghcr.io/samada58/${{ github.event.repository.name }}:latest
          format: 'table'
          cache-dir: ~/.trivy/db # Enable caching
          exit-code: '0'  # Don't fail the build on vulnerabilities, but list them
          severity: 'HIGH,CRITICAL' # Set the severity levels you care about

      # Push the Docker image to GitHub Packages
      - name: Push Docker Image to GitHub Packages
        run: |
          docker push ghcr.io/samada58/${{ github.event.repository.name }}:latest
