name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    name: Build and Publish Docker Image
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to the GitHub Container Registry
      - name: Log in to GitHub Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build the Docker image
      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/samada58/${{ github.event.repository.name }}:latest .

      # Scan Docker Image with Trivy
      - name: Scan Docker Image for vulnerabilities
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: ghcr.io/samada58/${{ github.event.repository.name }}:latest
          format: 'table'
          exit-code: '0' # Don't fail the build on vulnerabilities, but list them
          
      - name: Run Trivy scan
        run: |
          for i in {1..5}; do
            trivy image ghcr.io/samada58/ue19-lab-05:latest && break || sleep 60
          done

      # Push the Docker image to GitHub Packages
      - name: Push Docker Image to GitHub Packages
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest
